### ISSUE TITLE
[Bug Report]数据没有存入DB

### ISSUE THREAD

**Issue by bluejfox** [ume-team/ume-ems#1]
## **Steps to reproduce：**
服务ID:
EMS20002

请求内容：
["Create","UME_USER",{"USER_ID":"1111","USER_NAME":null,"USER_PASSWORD":null,"USER_MOBILE":null,"USER_NICK_NAME":null,"USER_HEAD_IMAGE":null,"USER_EMAIL":null,"USER_DESC":null,"USER_STATUS":0,"USER_GENDER":null}]

返回内容：
{"resultCode":0,"resultObject":1}

## **What is Expected?**
在服务没有错误返回的场合，数据能够正常存入DB。

## **What is actually happening?**
服务没有返回错误，但是数据没有存入DB。

**Comment by mmayye** [comment]
对同一Class在不同地方标记注解 @Bean 和 @Service 导致singleton scope时构造函数也多次初始化；
已修正。
